CREATE TABLE prices
( id INT AUTO_INCREMENT PRIMARY KEY,
BRAND_ID INT NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
PRICE_LIST INT NOT NULL,
PRODUCT_ID INT NOT NULL,
PRIORITY BIT NOT NULL,
PRICE NUMERIC NOT NULL,
CURRENCY VARCHAR(250) NOT NULL);